{
  allCards(pipeId: _PIPEID_, first:50) {
    edges {
      node {
        id
    fields {
      field {
        id
        type
				internal_id
      }
      name
      value
    }
    child_relations {
      id
      pipe {
        id
      }
      cards {
        id
        fields {
          field{
            id
          }
        }
      }
    } parent_relations {
      id
      cards {
        id
        fields {
          field{
            id
            label
          }
        }
      }
    }

  } 
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  } 
}

