{
  organizations{
    id
    name
    createdAt
    pipes {
     	id
			name
			start_form_fields{
        id	
        label
        type
        options
        editable
        deleted
        required
      }
			phases{
        id
        name
				description
				index
        fields{
          id
          label
          type
          options
          editable
					deleted
          required
        }
      }
    }
  }
}
