{
  card(id:_CARDID_){
    pipe{
      id
      organization{
        id
      }
    }
    	current_phase {
    	  id,
        name
    	}

        id
        title

    due_date
    overdue
    comments{
      id
      created_at
      text
      author {
        id
      }
    }

    labels {
      id
      name
    }
    fields {
      field {
        id
        type
        internal_id
      }
      name
      value
      updated_at
    }
    child_relations {
      id
      pipe {
        id
      }
      cards {
        id
        fields {
          field{
            id
          }
        }
      }
    } parent_relations {
      id
      cards {
        id
        fields {
          field{
            id
            label
          }
        }
      }
  }
}
}
