mutation{
  updateOrganization(
    input:{
    id: _ORGID_
    name: "_NAME_"
    only_admin_can_create_pipes: _ONLYADMINCANCREATEPIPE_ 
    only_admin_can_invite_users: _ONLYADMINCANINVITEUSER_
  }
  ) {
    clientMutationId
  }
}
