{
  organizations{
    id
    name
    createdAt
    tables{
      edges{
        node{
          id
          internal_id
          name
          description
          title_field{
            id
            
          }
          table_fields{
            id
            required
            deleted
            type
            options
            unique
            is_multiple
            internal_id
            label
          }
        }
      }
    }

    pipes {
        id
      	labels{
          id
          name
					color
        }
            name
            start_form_fields{
        id
        label
        type
        options
        editable
        deleted
        required
      }
            phases{
        id
        name
                description
                index
        fields{
          id
          label
          type
          options
          editable
                    deleted
          required
        }
      }
    }
  }
}
