{
  pipe(id:_PIPEID_) {
        id
        labels{
          id
          name
                    color
        }
            name
            start_form_fields{
        id
        label
        type
        options
        editable
        deleted
        required
      }
            phases{
        id
        name
                description
                index
        fields{
          id
          label
          type
          options
          editable
                    deleted
          required
        }
      }
    }
}
